### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by Nidev-lab** [Facundo-Fierro/Restorant-Baratie-Front#1]
## Proceso

1. Ingrese a la pagina.
2. Me quise crear un usuario.

## Resultado esperado

• Que al llenar el form de registro con los datos solicitados poder registrarme sin problemas.

## Resultado actual

• No puedo registrarme y sale un error pero no me dice que esta mal.

## Captura

![image](https://github.com/Facundo-Fierro/Restorant-Baratie-Front/assets/53904695/a517d2e0-95d1-46e2-b9bd-9c1a31573e21)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas Facundo! Como estas? Necesitaría que resuelvas este problema para poder continuar con la devolución del proyecto... Si tenes algún usuario con el que pueda loguearme porfa déjamelo comentado acá abajo o mándamelo por slack, Gracias!

**Comment by Facundo-Fierro** [comment]
Hola buenos dias,me podria pasar un wsp o algo por que se me bloqueo el
email por el extravio de mi celular y no puedo ingresar a slack,yo creo q
el problema esta en que el back end no debe estar corriendo,avise en el
mail que envie en el proyecto que no lo pude deployar por que me salia un
error que no sabia manejar, y al estar ya en la fecha de entrega lo mande
asi.Fijese si localmente no puede descargar el back end y ponerlo a correr
en la direccion que esta llamando axios en el front(local host 3000 si no
me equivoco)

**Comment by Nidev-lab** [comment]
Ahi te paso mi numero y vemos como hacemos para solucionarlo 3816980917
