### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by Nidev-lab** [Facundo-Fierro/Restorant-Baratie-Front#4]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.

## Resultado esperado

• Encontrar una seccion de menú con producto a pedir. 

## Resultado actual

• La  seccion de "menú" se encuentra vacia.

## Captura

![image](https://github.com/Facundo-Fierro/Restorant-Baratie-Front/assets/53904695/ec67a4c1-26ae-459a-9cff-2a37abfef6a0)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Facundo-Fierro** [comment]
Corregido,no agrego imagenes por que no se como hacer para que aparezcan en multiples paginas.
