### ISSUE TITLE
Pedidos

### ISSUE THREAD

**Issue by Nidev-lab** [Facundo-Fierro/Restorant-Baratie-Front#5]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.

## Resultado esperado

• No poder realizar pedidos si no tengo productos cargados.

## Resultado actual

• Puedo realizar un pedido vacio.

## Captura

![image](https://github.com/Facundo-Fierro/Restorant-Baratie-Front/assets/53904695/16aafc20-5ad4-4fcb-b691-04803824043f)
![image](https://github.com/Facundo-Fierro/Restorant-Baratie-Front/assets/53904695/da25a455-a795-4f10-ad51-43f2de63766a)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Facundo-Fierro** [comment]
Arreglado
